# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from enum import Enum
from azure.core import CaseInsensitiveEnumMeta


class ActionType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Enum. Indicates the action type. "Internal" refers to actions that are for internal only APIs."""

    INTERNAL = "Internal"


class AzureProvisioningState(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """The provisioning state of the resource."""

    SUCCEEDED = "Succeeded"
    """Resource has been created."""
    FAILED = "Failed"
    """Resource creation failed."""
    CANCELED = "Canceled"
    """Resource creation was canceled."""
    PROVISIONING = "Provisioning"
    """Resource is provisioning."""
    ACCEPTED = "Accepted"
    """Request on the resource has been accepted."""


class CreatedByType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """The type of identity that created the resource."""

    USER = "User"
    APPLICATION = "Application"
    MANAGED_IDENTITY = "ManagedIdentity"
    KEY = "Key"


class DatabaseCreateMode(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Create mode. Available options: Default - Create a database. Copy - Copy the source database
    (source database name must be specified) PointInTimeRestore - Create a database by restoring
    source database from a point in time (source database name and restore from time must be
    specified).
    """

    DEFAULT = "Default"
    """Create a database."""
    COPY = "Copy"
    """Copy the source database (source database name must be specified)."""
    POINT_IN_TIME_RESTORE = "PointInTimeRestore"
    """Create a database by restoring source database from a point in time (source database name and
    restore from time must be specified)."""


class IdentityType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Identity type of the main principal."""

    NONE = "None"
    """No identity."""
    USER_ASSIGNED = "UserAssigned"
    """User assigned identity."""


class Origin(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """The intended executor of the operation; as in Resource Based Access Control (RBAC) and audit
    logs UX. Default value is "user,system".
    """

    USER = "user"
    SYSTEM = "system"
    USER_SYSTEM = "user,system"


class PrincipalType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Principal type of the authorized principal."""

    APPLICATION = "Application"
    """Application principal type."""
    USER = "User"
    """User principal type."""


class ResourceType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Resource type of the destination tier override."""

    DATABASE = "Database"
    """Database resource type."""
    POOL = "Pool"
    """Elastic pool resource type."""


class ZoneRedundancy(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Status of zone redundancy in a tier."""

    ENABLED = "Enabled"
    """Zone redundancy enabled."""
    DISABLED = "Disabled"
    """Zone redundancy disabled."""
