[packaging]
package_name = "azure-mgmt-consumption"
package_nspkg = "azure-mgmt-nspkg"
package_pprint_name = "Consumption"
package_doc_id = "consumption"
is_stable = true
is_arm = true
sample_link = ""
title = "ConsumptionManagementClient"
