# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from ._models_py3 import Authority
from ._models_py3 import AuthorityListResult
from ._models_py3 import AuthorityProperties
from ._models_py3 import AuthorityUpdate
from ._models_py3 import ErrorAdditionalInfo
from ._models_py3 import ErrorDetail
from ._models_py3 import ErrorResponse
from ._models_py3 import Operation
from ._models_py3 import OperationDisplay
from ._models_py3 import OperationListResult
from ._models_py3 import Resource
from ._models_py3 import SystemData
from ._models_py3 import TrackedResource

from ._verified_id_mgmt_client_test_enums import ActionType
from ._verified_id_mgmt_client_test_enums import CreatedByType
from ._verified_id_mgmt_client_test_enums import Origin
from ._verified_id_mgmt_client_test_enums import ProvisioningState
from ._patch import __all__ as _patch_all
from ._patch import *  # pylint: disable=unused-wildcard-import
from ._patch import patch_sdk as _patch_sdk

__all__ = [
    "Authority",
    "AuthorityListResult",
    "AuthorityProperties",
    "AuthorityUpdate",
    "ErrorAdditionalInfo",
    "ErrorDetail",
    "ErrorResponse",
    "Operation",
    "OperationDisplay",
    "OperationListResult",
    "Resource",
    "SystemData",
    "TrackedResource",
    "ActionType",
    "CreatedByType",
    "Origin",
    "ProvisioningState",
]
__all__.extend([p for p in _patch_all if p not in __all__])
_patch_sdk()
