[packaging]
package_name = "azure-mgmt-peering"
package_nspkg = "azure-mgmt-nspkg"
package_pprint_name = "Peering Management"
package_doc_id = ""
is_stable = true
is_arm = true
title = "PeeringManagementClient"
