# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) Python Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------
import pytest
from azure.mgmt.toolchainorchestrator.aio import ToolchainOrchestratorClient

from devtools_testutils import AzureMgmtRecordedTestCase, RandomNameResourceGroupPreparer
from devtools_testutils.aio import recorded_by_proxy_async

AZURE_LOCATION = "eastus"


@pytest.mark.skip("you may need to update the auto-generated test case before run it")
class TestToolchainOrchestratorSolutionVersionsOperationsAsync(AzureMgmtRecordedTestCase):
    def setup_method(self, method):
        self.client = self.create_mgmt_client(ToolchainOrchestratorClient, is_async=True)

    @RandomNameResourceGroupPreparer(location=AZURE_LOCATION)
    @recorded_by_proxy_async
    async def test_solution_versions_get(self, resource_group):
        response = await self.client.solution_versions.get(
            resource_group_name=resource_group.name,
            solution_name="str",
            version_name="str",
        )

        # please add some check logic here by yourself
        # ...

    @RandomNameResourceGroupPreparer(location=AZURE_LOCATION)
    @recorded_by_proxy_async
    async def test_solution_versions_begin_create_or_update(self, resource_group):
        response = await (
            await self.client.solution_versions.begin_create_or_update(
                resource_group_name=resource_group.name,
                solution_name="str",
                version_name="str",
                resource={
                    "location": "str",
                    "extendedLocation": {"name": "str", "type": "str"},
                    "id": "str",
                    "name": "str",
                    "properties": {
                        "components": [
                            {
                                "name": "str",
                                "type": "str",
                                "constraints": "str",
                                "dependencies": ["str"],
                                "metadata": {"str": "str"},
                                "properties": {"str": {}},
                            }
                        ],
                        "displayName": "str",
                        "metadata": {"str": "str"},
                        "provisioningState": "str",
                    },
                    "systemData": {
                        "createdAt": "2020-02-20 00:00:00",
                        "createdBy": "str",
                        "createdByType": "str",
                        "lastModifiedAt": "2020-02-20 00:00:00",
                        "lastModifiedBy": "str",
                        "lastModifiedByType": "str",
                    },
                    "tags": {"str": "str"},
                    "type": "str",
                },
            )
        ).result()  # call '.result()' to poll until service return final result

        # please add some check logic here by yourself
        # ...

    @RandomNameResourceGroupPreparer(location=AZURE_LOCATION)
    @recorded_by_proxy_async
    async def test_solution_versions_begin_update(self, resource_group):
        response = await (
            await self.client.solution_versions.begin_update(
                resource_group_name=resource_group.name,
                solution_name="str",
                version_name="str",
                properties={"tags": {"str": "str"}},
            )
        ).result()  # call '.result()' to poll until service return final result

        # please add some check logic here by yourself
        # ...

    @RandomNameResourceGroupPreparer(location=AZURE_LOCATION)
    @recorded_by_proxy_async
    async def test_solution_versions_begin_delete(self, resource_group):
        response = await (
            await self.client.solution_versions.begin_delete(
                resource_group_name=resource_group.name,
                solution_name="str",
                version_name="str",
            )
        ).result()  # call '.result()' to poll until service return final result

        # please add some check logic here by yourself
        # ...

    @RandomNameResourceGroupPreparer(location=AZURE_LOCATION)
    @recorded_by_proxy_async
    async def test_solution_versions_list_by_solution(self, resource_group):
        response = self.client.solution_versions.list_by_solution(
            resource_group_name=resource_group.name,
            solution_name="str",
        )
        result = [r async for r in response]
        # please add some check logic here by yourself
        # ...
