[packaging]
package_name = "azure-mgmt-deployments-deploymentscripts"
package_nspkg = "azure-mgmt-deployments-nspkg"
package_pprint_name = "Deployments-deploymentscripts Management"
package_doc_id = ""
is_stable = true
is_arm = true
need_msrestazure = false
need_azuremgmtcore = true
sample_link = ""
exclude_folders = ""
title = "DeploymentScriptsClient"
