# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------
# pylint: disable=wrong-import-position

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ._patch import *  # pylint: disable=unused-wildcard-import

from ._operations import Operations  # type: ignore
from ._deleted_services_operations import DeletedServicesOperations  # type: ignore
from ._services_operations import ServicesOperations  # type: ignore
from ._metadata_schemas_operations import MetadataSchemasOperations  # type: ignore
from ._workspaces_operations import WorkspacesOperations  # type: ignore
from ._api_sources_operations import ApiSourcesOperations  # type: ignore
from ._apis_operations import ApisOperations  # type: ignore
from ._deployments_operations import DeploymentsOperations  # type: ignore
from ._api_versions_operations import ApiVersionsOperations  # type: ignore
from ._api_definitions_operations import ApiDefinitionsOperations  # type: ignore
from ._environments_operations import EnvironmentsOperations  # type: ignore

from ._patch import __all__ as _patch_all
from ._patch import *
from ._patch import patch_sdk as _patch_sdk

__all__ = [
    "Operations",
    "DeletedServicesOperations",
    "ServicesOperations",
    "MetadataSchemasOperations",
    "WorkspacesOperations",
    "ApiSourcesOperations",
    "ApisOperations",
    "DeploymentsOperations",
    "ApiVersionsOperations",
    "ApiDefinitionsOperations",
    "EnvironmentsOperations",
]
__all__.extend([p for p in _patch_all if p not in __all__])  # pyright: ignore
_patch_sdk()
