# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------
import pytest
from azure.mgmt.devcenter import DevCenterMgmtClient

from devtools_testutils import AzureMgmtRecordedTestCase, RandomNameResourceGroupPreparer, recorded_by_proxy

AZURE_LOCATION = "eastus"


@pytest.mark.skip("you may need to update the auto-generated test case before run it")
class TestDevCenterMgmtSchedulesOperations(AzureMgmtRecordedTestCase):
    def setup_method(self, method):
        self.client = self.create_mgmt_client(DevCenterMgmtClient)

    @RandomNameResourceGroupPreparer(location=AZURE_LOCATION)
    @recorded_by_proxy
    def test_schedules_list_by_pool(self, resource_group):
        response = self.client.schedules.list_by_pool(
            resource_group_name=resource_group.name,
            project_name="str",
            pool_name="str",
            api_version="2025-04-01-preview",
        )
        result = [r for r in response]
        # please add some check logic here by yourself
        # ...

    @RandomNameResourceGroupPreparer(location=AZURE_LOCATION)
    @recorded_by_proxy
    def test_schedules_get(self, resource_group):
        response = self.client.schedules.get(
            resource_group_name=resource_group.name,
            project_name="str",
            pool_name="str",
            schedule_name="str",
            api_version="2025-04-01-preview",
        )

        # please add some check logic here by yourself
        # ...

    @RandomNameResourceGroupPreparer(location=AZURE_LOCATION)
    @recorded_by_proxy
    def test_schedules_begin_create_or_update(self, resource_group):
        response = self.client.schedules.begin_create_or_update(
            resource_group_name=resource_group.name,
            project_name="str",
            pool_name="str",
            schedule_name="str",
            body={
                "frequency": "str",
                "id": "str",
                "location": "str",
                "name": "str",
                "provisioningState": "str",
                "state": "str",
                "systemData": {
                    "createdAt": "2020-02-20 00:00:00",
                    "createdBy": "str",
                    "createdByType": "str",
                    "lastModifiedAt": "2020-02-20 00:00:00",
                    "lastModifiedBy": "str",
                    "lastModifiedByType": "str",
                },
                "tags": {"str": "str"},
                "time": "str",
                "timeZone": "str",
                "type": "str",
            },
            api_version="2025-04-01-preview",
        ).result()  # call '.result()' to poll until service return final result

        # please add some check logic here by yourself
        # ...

    @RandomNameResourceGroupPreparer(location=AZURE_LOCATION)
    @recorded_by_proxy
    def test_schedules_begin_update(self, resource_group):
        response = self.client.schedules.begin_update(
            resource_group_name=resource_group.name,
            project_name="str",
            pool_name="str",
            schedule_name="str",
            body={
                "frequency": "str",
                "location": "str",
                "state": "str",
                "tags": {"str": "str"},
                "time": "str",
                "timeZone": "str",
                "type": "str",
            },
            api_version="2025-04-01-preview",
        ).result()  # call '.result()' to poll until service return final result

        # please add some check logic here by yourself
        # ...

    @RandomNameResourceGroupPreparer(location=AZURE_LOCATION)
    @recorded_by_proxy
    def test_schedules_begin_delete(self, resource_group):
        response = self.client.schedules.begin_delete(
            resource_group_name=resource_group.name,
            project_name="str",
            pool_name="str",
            schedule_name="str",
            api_version="2025-04-01-preview",
        ).result()  # call '.result()' to poll until service return final result

        # please add some check logic here by yourself
        # ...
