# pylint: disable=line-too-long,useless-suppression
# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from azure.identity import DefaultAzureCredential

from azure.mgmt.migrate import AzureMigrateDiscoveryService

"""
# PREREQUISITES
    pip install azure-identity
    pip install azure-mgmt-migrate
# USAGE
    python sql_sites_controller_error_summary_maximum_set_gen.py

    Before run the sample, please set the values of the client ID, tenant ID and client secret
    of the AAD application as environment variables: AZURE_CLIENT_ID, AZURE_TENANT_ID,
    AZURE_CLIENT_SECRET. For more info about how to get the value, please see:
    https://docs.microsoft.com/azure/active-directory/develop/howto-create-service-principal-portal
"""


def main():
    client = AzureMigrateDiscoveryService(
        credential=DefaultAzureCredential(),
        subscription_id="291F8922-D548-4CAF-9C43-C65300D5AFD4",
    )

    response = client.sql_sites_controller.error_summary(
        resource_group_name="rgmigrate",
        site_name="55--o3Q",
        sql_site_name="SQL-Server01",
        body={"applianceName": "fcskaactdnpczbpvam"},
    )
    print(response)


# x-ms-original-file: specification/migrate/resource-manager/Microsoft.OffAzure/preview/2024-12-01-preview/examples/SqlSitesController_ErrorSummary_MaximumSet_Gen.json
if __name__ == "__main__":
    main()
