[packaging]
package_name = "azure-mgmt-attestation"
package_nspkg = "azure-mgmt-nspkg"
package_pprint_name = "Attestation Management"
package_doc_id = ""
is_stable = true
is_arm = true
title = "AttestationManagementClient"
